#!/usr/bin/env node
/**
 * Builds research/benders/data/*.json from verified research constants.
 * Does not touch src/data/benders/.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DATA = path.resolve(__dirname, '../data');
const DATE = '2026-07-14';

function frac(s) {
  // "4-3/16" | "5-1/8" | "7-1/2" | "13 1/2" | "3.69" | "21 1/2"
  if (typeof s === 'number') return s;
  const t = String(s).trim().replace(/"/g, '').replace(/″/g, '');
  if (/^\d+(\.\d+)?$/.test(t)) return Number(t);
  const m1 = t.match(/^(\d+)-(\d+)\/(\d+)$/);
  if (m1) return Number(m1[1]) + Number(m1[2]) / Number(m1[3]);
  const m2 = t.match(/^(\d+)\s+(\d+)\/(\d+)$/);
  if (m2) return Number(m2[1]) + Number(m2[2]) / Number(m2[3]);
  const m3 = t.match(/^(\d+)\/(\d+)$/);
  if (m3) return Number(m3[1]) / Number(m3[2]);
  throw new Error(`Cannot parse fraction: ${s}`);
}

const manufacturers = [
  {
    id: 'mfr-greenlee',
    name: 'Greenlee',
    aliases: ['Greenlee Tools', 'Greenlee Textron'],
    website: 'https://www.greenlee.com/',
    regions: ['US', 'CA'],
    notes: 'Primary official source for Site-Rite hand, 555 electric, 881 hydraulic families.',
  },
  {
    id: 'mfr-klein',
    name: 'Klein Tools',
    aliases: ['Klein'],
    website: 'https://www.kleintools.com/',
    regions: ['US', 'CA', 'UK'],
    notes: 'Angle Setter hand-bender family with published stub-up and centerline radius on product pages.',
  },
  {
    id: 'mfr-gardner-bender',
    name: 'Gardner Bender',
    aliases: ['GB', 'Gardner Bender / ECM'],
    website: 'https://www.gardnerbender.com/',
    regions: ['US', 'CA'],
    notes: 'BigBen aluminum hand benders; Sidewinder B2555 electric; legacy iron/Benfield-style lines.',
  },
  {
    id: 'mfr-ideal',
    name: 'IDEAL',
    aliases: ['IDEAL Electrical', 'Ideal Industries'],
    website: 'https://idealelectricalinc.com/',
    regions: ['US', 'CA'],
    notes: 'Aluminum and ductile-iron hand heads publish stub-up; no official CLR found on product pages.',
  },
  {
    id: 'mfr-milwaukee',
    name: 'Milwaukee',
    aliases: ['Milwaukee Tool'],
    website: 'https://www.milwaukeetool.com/',
    regions: ['US', 'CA'],
    notes: 'Hand benders identity/capacity confirmed; no published stub-up or radius on product pages.',
  },
  {
    id: 'mfr-southwire',
    name: 'Southwire',
    aliases: [],
    website: 'https://www.southwire.com/',
    regions: ['US'],
    notes: 'MCB hand bender cutsheet confirms models; no published take-up/radius in cutsheet research.',
  },
  {
    id: 'mfr-current-tools',
    name: 'Current Tools',
    aliases: ['Current Tools Inc'],
    website: 'https://currenttools.com/',
    regions: ['US'],
    notes: 'Mechanical 750/753, electric 77 series, hydraulic 254 — official manuals with deduct charts.',
  },
  {
    id: 'mfr-ridgid',
    name: 'RIDGID',
    aliases: ['Ridge Tool', 'Emerson RIDGID'],
    website: 'https://www.ridgid.com/',
    regions: ['US', 'EU'],
    notes:
      'Hydraulic pipe benders are generally schedule pipe, not EMT conduit charts. E-666 electric conduit bender appears in distributor literature; treat as reference-only until RIDGID official chart verified.',
  },
  {
    id: 'mfr-rack-a-tiers',
    name: 'Rack-A-Tiers',
    aliases: [],
    website: 'https://rack-a-tiers.com/',
    regions: ['US', 'CA'],
    notes: 'Hoppy Bender and Skybender identity verified on official site; no stub-up/radius chart published on product pages reviewed.',
  },
  {
    id: 'mfr-benfield',
    name: 'Benfield',
    aliases: ['Jack Benfield', 'Benfield Manufacturing'],
    website: null,
    regions: ['US'],
    notes:
      'Historic brand / method author. Benfield Conduit Bending Manual is instructional literature, not a current OEM shoe chart for a living SKU line. Reference-only.',
  },
  {
    id: 'mfr-nsi',
    name: 'NSI Industries',
    aliases: ['NSI', 'Tork'],
    website: 'https://www.nsiindustries.com/',
    regions: ['US'],
    notes: 'Research lead for house-brand / Tork lines — no authoritative EMT hand-bender take-up chart located in this pass.',
  },
  {
    id: 'mfr-emerson-chicago',
    name: 'Chicago / Emerson legacy',
    aliases: ['Chicago Bender', 'Emerson Electric legacy ratchet'],
    website: null,
    regions: ['US'],
    notes: 'Legacy ratchet/"Chicago" style mechanical benders referenced in trade literature; exact current OEM ownership and charts blocked without identifiable official revision.',
  },
];

const sources = [
  {
    id: 'src-greenlee-site-rite-cdn',
    publisher: 'Greenlee',
    manufacturerId: 'mfr-greenlee',
    title: 'Aluminum and Iron Site-Rite Single and Dual Shoe Hand Benders use guide',
    url: 'https://cdn.greenlee.com/resources/media?key=1adba548-f1d2-43d2-bf44-fe4b89a8b579&languageCode=en&type=document',
    sourceType: 'official_pdf_manual',
    retrievalDate: DATE,
    publicationOrRevisionDate: 'Rev. 3 (production cites 52087654 Rev. 3)',
    region: 'US',
    currency: 'current',
    modelsCovered: ['840A', '840AH', '841A', '841AH', '842A', '842AH', '843A', '843AH', '840F', '840FH', '841F', '841FH', '842F', '842FH', '843F', '843FH', '844A', '844AH'],
    pageTableOrSection: 'Specifications / deduct & bend radius table',
    excerpt: 'Site-Rite hand bender deduct and bend radius by catalog number',
    accessNotes: 'Official CDN document used by Bend Pro production workbook v1.1.',
    redistributionLicenseStatus: 'url_reference_only',
    contentChecksum: null,
  },
  {
    id: 'src-greenlee-site-rite-manualsnet-mirror',
    publisher: 'Greenlee (mirror host Manualsnet)',
    manufacturerId: 'mfr-greenlee',
    title: 'Greenlee Aluminum and Iron Site-Rite User Manual (table extract)',
    url: 'https://manualsnet.com/greenlee/aluminum-and-iron-site-rite',
    sourceType: 'authorized_distributor_doc',
    retrievalDate: DATE,
    publicationOrRevisionDate: '552034125 REV 02 2023 (as shown on mirrored pages)',
    region: 'US',
    currency: 'archived',
    modelsCovered: ['840A', '841A', '842A', '843A', '840F', '841F', '842F', '843F', '844A'],
    pageTableOrSection: 'Specifications MODEL CATALOG # BEND RADIUS / DEDUCT',
    excerpt: '840A/AH 4-3/16 bend radius, 5 deduct; dual shoe 844A/AH listed',
    accessNotes: 'Secondary host of manufacturer manual content; corroboration only — prefer CDN official.',
    redistributionLicenseStatus: 'url_reference_only',
    contentChecksum: null,
  },
  {
    id: 'src-greenlee-843a-product',
    publisher: 'Greenlee',
    manufacturerId: 'mfr-greenlee',
    title: 'Aluminum Hand Bender Head 1-1/4 EMT / 1 Rigid — 843A',
    url: 'https://www.greenlee.com/us/en/benderhand---1-1-4-emt--1-rigid-843a',
    sourceType: 'official_product_page',
    retrievalDate: DATE,
    publicationOrRevisionDate: null,
    region: 'US',
    currency: 'current',
    modelsCovered: ['843A'],
    pageTableOrSection: 'Specifications — Centerline Bend Radius',
    excerpt: 'Centerline Bend Radius 9-5/8 in for 1-1/4 EMT',
    accessNotes: 'Confirms CLR for 843A; does not alone prove full family table.',
    redistributionLicenseStatus: 'url_reference_only',
    contentChecksum: null,
  },
  {
    id: 'src-greenlee-555-single-shoe-52065584-rev02',
    publisher: 'Greenlee',
    manufacturerId: 'mfr-greenlee',
    title: 'Single-Shoe Groups for 555 Series Electric Benders — 52065584 REV02',
    url: 'https://greenlee-cdn.ebizcdn.com/media/52065584REV02.pdf',
    sourceType: 'official_pdf_manual',
    retrievalDate: DATE,
    publicationOrRevisionDate: '52065584 REV02',
    region: 'US',
    currency: 'current',
    modelsCovered: ['555C', '555CX', '555DX', '555DX-22', '555CX-22', '23803', '13934', '28008'],
    pageTableOrSection: 'Deduct Table; Centerline Bending Radii for EMT, IMC, and Rigid Shoe Groups',
    excerpt: 'EMT deduct 7-1/2 to 16-3/8; EMT CLR 4-5/16 to 9-1/4 by size',
    accessNotes: 'Figures marked approximate on deduct table. Frame vs shoe: values apply to shoe groups on 555 series.',
    redistributionLicenseStatus: 'url_reference_only',
    contentChecksum: null,
  },
  {
    id: 'src-greenlee-23803-product',
    publisher: 'Greenlee',
    manufacturerId: 'mfr-greenlee',
    title: 'EMT Shoe Group 1/2-2 for 555C — Cat 23803',
    url: 'https://www.greenlee.com/us/en/emt-shoe-group--1-2---2-23803',
    sourceType: 'official_product_page',
    retrievalDate: DATE,
    publicationOrRevisionDate: null,
    region: 'US',
    currency: 'current',
    modelsCovered: ['23803', '555C'],
    pageTableOrSection: 'Specifications — Centerline Bend Radius',
    excerpt: 'Lists Centerline Bend Radius 1/2 4-1/4 through 2 9',
    accessNotes:
      'CONFLICT: page lists values matching Rigid/IMC column of 52065584REV02, not the EMT column. Do not promote without human review.',
    redistributionLicenseStatus: 'url_reference_only',
    contentChecksum: null,
  },
  {
    id: 'src-greenlee-2015-bending-catalog',
    publisher: 'Greenlee',
    manufacturerId: 'mfr-greenlee',
    title: 'Greenlee Bending catalog excerpt (2015 Bending.pdf)',
    url: 'https://greenlee-cdn.ebizcdn.com/media/2015%20Bending.pdf',
    sourceType: 'official_catalog',
    retrievalDate: DATE,
    publicationOrRevisionDate: '2015',
    region: 'US',
    currency: 'archived',
    modelsCovered: ['555C', '555CX', '555DX', '881CT', '880', '884', '885', '855GX'],
    pageTableOrSection: 'Shoe groups; 881 CT centerline radii; 880 radii',
    excerpt: '881 CT centerline radii 13-1/2 to 20-7/8 by size; 880 radii table',
    accessNotes: 'Archived catalog — confirm against current product pages before production promotion.',
    redistributionLicenseStatus: 'url_reference_only',
    contentChecksum: null,
  },
  {
    id: 'src-greenlee-881-4in-shoe-31274',
    publisher: 'Greenlee',
    manufacturerId: 'mfr-greenlee',
    title: '4 inch One-Shot 90 EMT IMC Rigid Shoe Group 31274',
    url: 'https://www.greenlee.com/us/en/4-inch-ct-group-31274',
    sourceType: 'official_product_page',
    retrievalDate: DATE,
    publicationOrRevisionDate: null,
    region: 'US',
    currency: 'current',
    modelsCovered: ['31274', '881CT', '881'],
    pageTableOrSection: 'Specifications — Centerline Bend Radius',
    excerpt: 'Centerline Bend Radius 20-7/8 in for 4 in one-shot shoe',
    accessNotes: '',
    redistributionLicenseStatus: 'url_reference_only',
    contentChecksum: null,
  },
  {
    id: 'src-greenlee-884-885-radii-cdn',
    publisher: 'Greenlee',
    manufacturerId: 'mfr-greenlee',
    title: 'Centerline bending radii for 884 and 885 benders (CDN media)',
    url: 'https://cdn.greenlee.com/resources/media?key=7b356e19-00c8-41d3-8e38-0c2c4325930b&languageCode=en',
    sourceType: 'official_bulletin',
    retrievalDate: DATE,
    publicationOrRevisionDate: null,
    region: 'US',
    currency: 'unknown',
    modelsCovered: ['884', '885'],
    pageTableOrSection: 'Centerline Bending Radii for the 884 and 885 Benders',
    excerpt: 'Rigid shoe size radii 4 through 25 inches by trade size',
    accessNotes: 'Table labeled Rigid Shoe Size — mark non-EMT / out of production scope unless EMT explicitly shown.',
    redistributionLicenseStatus: 'url_reference_only',
    contentChecksum: null,
  },
  {
    id: 'src-klein-51604',
    publisher: 'Klein Tools',
    manufacturerId: 'mfr-klein',
    title: 'Iron Conduit Bender Full Assembly 3/4 EMT Angle Setter — 51604',
    url: 'https://www.kleintools.com/catalog/conduit-benders-and-parts/iron-conduit-bender-full-assembly-34-inch-emt-angle-setter',
    sourceType: 'official_product_page',
    retrievalDate: DATE,
    publicationOrRevisionDate: null,
    region: 'US',
    currency: 'current',
    modelsCovered: ['51604', '51609', '51612'],
    pageTableOrSection: 'Specifications',
    excerpt: 'Centerline Bend Radius 5.5; Stub-Up Height 6',
    accessNotes: '',
    redistributionLicenseStatus: 'url_reference_only',
    contentChecksum: null,
  },
  {
    id: 'src-klein-51606',
    publisher: 'Klein Tools',
    manufacturerId: 'mfr-klein',
    title: 'Aluminum Conduit Bender Full Assembly 1/2 EMT Angle Setter — 51606',
    url: 'https://www.kleintools.com/catalog/conduit-benders-and-parts/aluminum-conduit-bender-full-assembly-12-inch-emt-angle-setter',
    sourceType: 'official_product_page',
    retrievalDate: DATE,
    publicationOrRevisionDate: null,
    region: 'US',
    currency: 'current',
    modelsCovered: ['51606', '51611'],
    pageTableOrSection: 'Specifications',
    excerpt: 'Centerline Bend Radius 4.625; Stub-Up Height 5',
    accessNotes: '',
    redistributionLicenseStatus: 'url_reference_only',
    contentChecksum: null,
  },
  {
    id: 'src-klein-51608',
    publisher: 'Klein Tools',
    manufacturerId: 'mfr-klein',
    title: '1/2-inch Iron Conduit Bender Head — 51608',
    url: 'https://www.kleintools.com/catalog/conduit-tool-accessories-and-replacement-parts/12-inch-iron-conduit-bender-head',
    sourceType: 'official_product_page',
    retrievalDate: DATE,
    publicationOrRevisionDate: null,
    region: 'US',
    currency: 'current',
    modelsCovered: ['51608', '51603'],
    pageTableOrSection: 'Specifications',
    excerpt: 'Iron head for 1/2 EMT Angle Setter family',
    accessNotes: 'Production cites stub-up/radius from this page family.',
    redistributionLicenseStatus: 'url_reference_only',
    contentChecksum: null,
  },
  {
    id: 'src-klein-51607',
    publisher: 'Klein Tools',
    manufacturerId: 'mfr-klein',
    title: 'Aluminum Conduit Bender Full Assembly 3/4 EMT Angle Setter — 51607',
    url: 'https://www.kleintools.com/catalog/conduit-benders-and-parts/aluminum-conduit-bender-full-assembly-34-inch-emt-angle-setter',
    sourceType: 'official_product_page',
    retrievalDate: DATE,
    publicationOrRevisionDate: null,
    region: 'US',
    currency: 'current',
    modelsCovered: ['51607'],
    pageTableOrSection: 'Specifications',
    excerpt: 'Aluminum 3/4 EMT Angle Setter assembly',
    accessNotes: '',
    redistributionLicenseStatus: 'url_reference_only',
    contentChecksum: null,
  },
  {
    id: 'src-klein-51610',
    publisher: 'Klein Tools',
    manufacturerId: 'mfr-klein',
    title: '1-Inch Iron Conduit Bender Head — 51610',
    url: 'https://www.kleintools.com/catalog/conduit-tool-accessories-and-replacement-parts/1-inch-iron-conduit-bender-head',
    sourceType: 'official_product_page',
    retrievalDate: DATE,
    publicationOrRevisionDate: null,
    region: 'US',
    currency: 'current',
    modelsCovered: ['51610', '51605'],
    pageTableOrSection: 'Specifications',
    excerpt: '1-inch iron head Angle Setter family',
    accessNotes: '',
    redistributionLicenseStatus: 'url_reference_only',
    contentChecksum: null,
  },
  {
    id: 'src-gardner-howto-gar-bro-032',
    publisher: 'Gardner Bender',
    manufacturerId: 'mfr-gardner-bender',
    title: 'Hand Benders How To Guide GAR_BRO_032_1220',
    url: 'https://www.gardnerbender.com/-/media/inriver/GAR_BRO_032_1220_Hand%20Bender%20How%20To%20Guide.pdf',
    sourceType: 'official_pdf_guide',
    retrievalDate: DATE,
    publicationOrRevisionDate: '1220',
    region: 'US',
    currency: 'current',
    modelsCovered: ['960', '961', '962', '960H', '961H', '962H'],
    pageTableOrSection: 'Table 1 EMT Deduct; Aluminum BigBen radius table',
    excerpt: 'EMT deduct 5/6/8; BigBen radii 3.69 / 4.74 / 5.81',
    accessNotes: 'Do not confuse with older B-0040 which mislabels deduct as radius.',
    redistributionLicenseStatus: 'url_reference_only',
    contentChecksum: null,
  },
  {
    id: 'src-gardner-b0040-legacy-mislabeled',
    publisher: 'Gardner Bender',
    manufacturerId: 'mfr-gardner-bender',
    title: 'Legacy B-0040 How To Guide (mislabeled radius column) — reference conflict',
    url: 'https://www.gardnerbender.com/-/media/inriver/GAR_BRO_032_1220_Hand%20Bender%20How%20To%20Guide.pdf',
    sourceType: 'archived_official',
    retrievalDate: DATE,
    publicationOrRevisionDate: 'B-0040 (superseded; exact archived URL not retained in-repo)',
    region: 'US',
    currency: 'archived',
    modelsCovered: ['960', '961', '962'],
    pageTableOrSection: 'Radius column (incorrect — contains deduct values)',
    excerpt: 'Legacy guide mislabels deduct 5/6/8 as radius',
    accessNotes:
      'Documented via Bend Pro production sourceNote and current guide warning. Do not redistribute; conflict evidence only.',
    redistributionLicenseStatus: 'url_reference_only',
    contentChecksum: null,
  },
  {
    id: 'src-ideal-74-006-related',
    publisher: 'IDEAL',
    manufacturerId: 'mfr-ideal',
    title: 'Related-product navigation cites 74-006 as 1-1/4 EMT ductile iron head',
    url: 'https://idealelectricalinc.com/en-ca/product/ductile-iron-bender-head-1-2-emt/',
    sourceType: 'official_product_page',
    retrievalDate: DATE,
    publicationOrRevisionDate: null,
    region: 'CA',
    currency: 'current',
    modelsCovered: ['74-006'],
    pageTableOrSection: 'Related Products',
    excerpt: 'Related products list Ductile Iron Bender Head 1-1/4 EMT SKU 74-006',
    accessNotes: 'Discovery lead from related-products nav — open dedicated 74-006 page before promoting numbers.',
    redistributionLicenseStatus: 'url_reference_only',
    contentChecksum: null,
  },
  {
    id: 'src-gardner-npa-759-bigben',
    publisher: 'Gardner Bender',
    manufacturerId: 'mfr-gardner-bender',
    title: 'BigBen Aluminum Hand Bender product sheet NPA-759',
    url: 'https://www.gardnerbender.com/-/media/inriver/NPA-759.pdf',
    sourceType: 'official_pdf_product_sheet',
    retrievalDate: DATE,
    publicationOrRevisionDate: 'NPA-759',
    region: 'US',
    currency: 'current',
    modelsCovered: ['960', '961', '962'],
    pageTableOrSection: 'Product specifications',
    excerpt: 'BigBen aluminum hand bender product sheet',
    accessNotes: '',
    redistributionLicenseStatus: 'url_reference_only',
    contentChecksum: null,
  },
  {
    id: 'src-gardner-b2555-is-002',
    publisher: 'Gardner Bender',
    manufacturerId: 'mfr-gardner-bender',
    title: 'B2555 Series Electric Sidewinder Instruction Sheet IS_002',
    url: 'https://www.gardnerbender.com/-/media/inriver/IS_002.pdf?modified=20200714153217',
    sourceType: 'official_pdf_manual',
    retrievalDate: DATE,
    publicationOrRevisionDate: 'IS_002 September (sheet header)',
    region: 'US',
    currency: 'current',
    modelsCovered: ['B2555', 'B2555EMT', 'B2555RIG', 'B2555IMC', 'B2555PVC', 'BEMT-52'],
    pageTableOrSection: 'Chart B EMT Deduct; bending radius table; shoe interchange note',
    excerpt: 'EMT deduct 7 through 15-3/8; shoes interchange with Greenlee 555 PL/AAJ',
    accessNotes: 'Springback approximate. Min stub = deduct + 2 inches.',
    redistributionLicenseStatus: 'url_reference_only',
    contentChecksum: null,
  },
  {
    id: 'src-gardner-b2555-product',
    publisher: 'Gardner Bender',
    manufacturerId: 'mfr-gardner-bender',
    title: 'Electric Sidewinder Bender B2555 product page',
    url: 'https://www.gardnerbender.com/en/p/B2555/Electric-Sidewinder-Bender-110-115-VAC',
    sourceType: 'official_product_page',
    retrievalDate: DATE,
    publicationOrRevisionDate: null,
    region: 'US',
    currency: 'current',
    modelsCovered: ['B2555'],
    pageTableOrSection: 'Product overview',
    excerpt: '110/115 VAC 20 Amp; interchangeable shoes; up to 180 degree bends',
    accessNotes: '',
    redistributionLicenseStatus: 'url_reference_only',
    contentChecksum: null,
  },
  {
    id: 'src-ideal-74-031',
    publisher: 'IDEAL',
    manufacturerId: 'mfr-ideal',
    title: 'Aluminum Bender Head 1/2 EMT — 74-031',
    url: 'https://idealelectricalinc.com/product/aluminum-bender-head-1-2-emt/',
    sourceType: 'official_product_page',
    retrievalDate: DATE,
    publicationOrRevisionDate: null,
    region: 'US',
    currency: 'current',
    modelsCovered: ['74-031'],
    pageTableOrSection: 'Key Specifications — Stub Up Height',
    excerpt: 'Stub Up Height 5 inches for 1/2 EMT aluminum head',
    accessNotes: 'No centerline radius published on page.',
    redistributionLicenseStatus: 'url_reference_only',
    contentChecksum: null,
  },
  {
    id: 'src-ideal-74-032',
    publisher: 'IDEAL',
    manufacturerId: 'mfr-ideal',
    title: 'Aluminum Bender Head 3/4 EMT — 74-032',
    url: 'https://idealelectricalinc.com/product/aluminum-bender-head-3-4-emt/',
    sourceType: 'official_product_page',
    retrievalDate: DATE,
    publicationOrRevisionDate: null,
    region: 'US',
    currency: 'current',
    modelsCovered: ['74-032'],
    pageTableOrSection: 'Key Specifications — Stub Up Height',
    excerpt: 'Stub Up Height 6 inches; also lists Rigid/IMC Size 1/2',
    accessNotes: 'No centerline radius published on page.',
    redistributionLicenseStatus: 'url_reference_only',
    contentChecksum: null,
  },
  {
    id: 'src-ideal-74-001',
    publisher: 'IDEAL',
    manufacturerId: 'mfr-ideal',
    title: 'Ductile Iron Bender Head 1/2 EMT — 74-001',
    url: 'https://idealelectricalinc.com/en-ca/product/ductile-iron-bender-head-1-2-emt/',
    sourceType: 'official_product_page',
    retrievalDate: DATE,
    publicationOrRevisionDate: null,
    region: 'CA',
    currency: 'current',
    modelsCovered: ['74-001'],
    pageTableOrSection: 'Key Specifications — Stub Up Height',
    excerpt: 'Stub Up Height 5 inches for 1/2 EMT ductile iron head',
    accessNotes: 'CA locale page; content matches US catalog expectations.',
    redistributionLicenseStatus: 'url_reference_only',
    contentChecksum: null,
  },
  {
    id: 'src-ideal-74-002',
    publisher: 'IDEAL',
    manufacturerId: 'mfr-ideal',
    title: 'Ductile Iron Bender Head 3/4 EMT — 74-002',
    url: 'https://idealelectricalinc.com/product/ductile-iron-bender-head-3-4-emt/',
    sourceType: 'official_product_page',
    retrievalDate: DATE,
    publicationOrRevisionDate: null,
    region: 'US',
    currency: 'current',
    modelsCovered: ['74-002'],
    pageTableOrSection: 'Key Specifications — Stub Up Height',
    excerpt: 'Stub Up Height 6 inches for 3/4 EMT ductile iron head',
    accessNotes: '',
    redistributionLicenseStatus: 'url_reference_only',
    contentChecksum: null,
  },
  {
    id: 'src-ideal-74-003',
    publisher: 'IDEAL',
    manufacturerId: 'mfr-ideal',
    title: 'Ductile Iron Bender Head 1 EMT — 74-003',
    url: 'https://idealelectricalinc.com/product/ductile-iron-bender-head-1-emt/',
    sourceType: 'official_product_page',
    retrievalDate: DATE,
    publicationOrRevisionDate: null,
    region: 'US',
    currency: 'current',
    modelsCovered: ['74-003'],
    pageTableOrSection: 'Key Specifications',
    excerpt: 'Ductile iron 1 EMT head (stub-up per production 8 in — re-verify on page)',
    accessNotes: 'Confirm stub-up on live page during promotion; related-product links cite 74-003 as 1 EMT.',
    redistributionLicenseStatus: 'url_reference_only',
    contentChecksum: null,
  },
  {
    id: 'src-ideal-74-034',
    publisher: 'IDEAL',
    manufacturerId: 'mfr-ideal',
    title: 'Ductile Iron Bender w/ Handle 1-1/4 EMT — 74-034',
    url: 'https://idealelectricalinc.com/product/ductile-iron-bender-w-handle-1-1-4-emt/',
    sourceType: 'official_product_page',
    retrievalDate: DATE,
    publicationOrRevisionDate: null,
    region: 'US',
    currency: 'unknown',
    modelsCovered: ['74-034'],
    pageTableOrSection: 'Key Specifications',
    excerpt: 'Production cites stub-up 11 for 1-1/4 EMT assembly',
    accessNotes:
      'Related products also list 74-006 as 1-1/4 EMT head — verify whether 74-034 remains current assembly SKU.',
    redistributionLicenseStatus: 'url_reference_only',
    contentChecksum: null,
  },
  {
    id: 'src-milwaukee-48-22-4070',
    publisher: 'Milwaukee',
    manufacturerId: 'mfr-milwaukee',
    title: '1/2 EMT Aluminum Conduit Bender — 48-22-4070',
    url: 'https://www.milwaukeetool.com/products/48-22-4070',
    sourceType: 'official_product_page',
    retrievalDate: DATE,
    publicationOrRevisionDate: null,
    region: 'US',
    currency: 'current',
    modelsCovered: ['48-22-4070'],
    pageTableOrSection: 'Product Overview',
    excerpt: 'For 1/2 EMT aluminum bender; no stub-up or radius published',
    accessNotes: 'Identity only.',
    redistributionLicenseStatus: 'url_reference_only',
    contentChecksum: null,
  },
  {
    id: 'src-milwaukee-48-22-4071',
    publisher: 'Milwaukee',
    manufacturerId: 'mfr-milwaukee',
    title: '3/4 EMT Aluminum Conduit Bender — 48-22-4071',
    url: 'https://www.milwaukeetool.com/products/48-22-4071',
    sourceType: 'official_product_page',
    retrievalDate: DATE,
    publicationOrRevisionDate: null,
    region: 'US',
    currency: 'current',
    modelsCovered: ['48-22-4071'],
    pageTableOrSection: 'Product Overview',
    excerpt: '3/4 EMT aluminum conduit bender identity',
    accessNotes: '',
    redistributionLicenseStatus: 'url_reference_only',
    contentChecksum: null,
  },
  {
    id: 'src-milwaukee-48-22-4072',
    publisher: 'Milwaukee',
    manufacturerId: 'mfr-milwaukee',
    title: '1 EMT Aluminum Conduit Bender — 48-22-4072',
    url: 'https://www.milwaukeetool.com/products/48-22-4072',
    sourceType: 'official_product_page',
    retrievalDate: DATE,
    publicationOrRevisionDate: null,
    region: 'US',
    currency: 'current',
    modelsCovered: ['48-22-4072'],
    pageTableOrSection: 'Product Overview',
    excerpt: '1 EMT aluminum conduit bender identity',
    accessNotes: '',
    redistributionLicenseStatus: 'url_reference_only',
    contentChecksum: null,
  },
  {
    id: 'src-milwaukee-48-22-4080',
    publisher: 'Milwaukee',
    manufacturerId: 'mfr-milwaukee',
    title: '1/2 EMT Iron Conduit Bender — 48-22-4080',
    url: 'https://www.milwaukeetool.com/products/48-22-4080',
    sourceType: 'official_product_page',
    retrievalDate: DATE,
    publicationOrRevisionDate: null,
    region: 'US',
    currency: 'current',
    modelsCovered: ['48-22-4080'],
    pageTableOrSection: 'Product Overview',
    excerpt: '1/2 EMT iron conduit bender identity',
    accessNotes: '',
    redistributionLicenseStatus: 'url_reference_only',
    contentChecksum: null,
  },
  {
    id: 'src-milwaukee-48-22-4081',
    publisher: 'Milwaukee',
    manufacturerId: 'mfr-milwaukee',
    title: '3/4 EMT Iron Conduit Bender — 48-22-4081',
    url: 'https://www.milwaukeetool.com/products/48-22-4081',
    sourceType: 'official_product_page',
    retrievalDate: DATE,
    publicationOrRevisionDate: null,
    region: 'US',
    currency: 'current',
    modelsCovered: ['48-22-4081'],
    pageTableOrSection: 'Product Overview',
    excerpt: '3/4 EMT iron conduit bender identity',
    accessNotes: '',
    redistributionLicenseStatus: 'url_reference_only',
    contentChecksum: null,
  },
  {
    id: 'src-milwaukee-48-22-4082',
    publisher: 'Milwaukee',
    manufacturerId: 'mfr-milwaukee',
    title: '1 EMT Iron Conduit Bender — 48-22-4082',
    url: 'https://www.milwaukeetool.com/products/48-22-4082',
    sourceType: 'official_product_page',
    retrievalDate: DATE,
    publicationOrRevisionDate: null,
    region: 'US',
    currency: 'current',
    modelsCovered: ['48-22-4082'],
    pageTableOrSection: 'Product Overview',
    excerpt: '1 EMT iron conduit bender identity',
    accessNotes: '',
    redistributionLicenseStatus: 'url_reference_only',
    contentChecksum: null,
  },
  {
    id: 'src-southwire-2024-hand-benders',
    publisher: 'Southwire',
    manufacturerId: 'mfr-southwire',
    title: 'Conduit Hand Benders cutsheet 2401',
    url: 'https://www.southwire.com/medias/2401-Hand-Benders-Cutsheet-WEB.pdf',
    sourceType: 'official_pdf_product_sheet',
    retrievalDate: DATE,
    publicationOrRevisionDate: '2024 cutsheet filename 2401',
    region: 'US',
    currency: 'unknown',
    modelsCovered: ['MCB1/2', 'MCB3/4', 'MCB1', '58281340', '58281240', '58281440'],
    pageTableOrSection: 'Product cutsheet',
    excerpt: 'MCB hand bender models and capacities',
    accessNotes: 'Direct PDF fetch returned HTTP 400 on 2026-07-14; production URL retained — re-verify access.',
    redistributionLicenseStatus: 'url_reference_only',
    contentChecksum: null,
  },
  {
    id: 'src-current-tools-254',
    publisher: 'Current Tools',
    manufacturerId: 'mfr-current-tools',
    title: 'Model 254 Hydraulic Conduit Bender manual',
    url: 'https://currenttools.com/wp-content/uploads/2020/12/254-Bender-C.pdf',
    sourceType: 'official_pdf_manual',
    retrievalDate: DATE,
    publicationOrRevisionDate: null,
    region: 'US',
    currency: 'current',
    modelsCovered: ['254', '254-111', '254-118', '254-125', '254-132'],
    pageTableOrSection: 'Chart B EMT; Centerline Bending Radii; shoe kits',
    excerpt: 'EMT deduct 21-1/2 to 32-1/4; CLR 13-1/2 to 21 by size',
    accessNotes: 'One-shot hydraulic; shoes also noted compatible with Greenlee 881CT CamTrack in manual.',
    redistributionLicenseStatus: 'url_reference_only',
    contentChecksum: null,
  },
  {
    id: 'src-current-tools-753',
    publisher: 'Current Tools',
    manufacturerId: 'mfr-current-tools',
    title: 'Model 753 Mechanical Bender manual',
    url: 'https://currenttools.com/images/pdf/manuals/new_manuals_with_disclaimer_2020/753_Mechanical_Bender.pdf',
    sourceType: 'official_pdf_manual',
    retrievalDate: DATE,
    publicationOrRevisionDate: null,
    region: 'US',
    currency: 'current',
    modelsCovered: ['753'],
    pageTableOrSection: 'Chart B EMT Deduct',
    excerpt: 'Mechanical bender 1/2-1-1/4 EMT capacity with deduct charts',
    accessNotes: 'Full EMT deduct row values need careful re-read of Chart B before promotion; Rigid chart excerpted in research.',
    redistributionLicenseStatus: 'url_reference_only',
    contentChecksum: null,
  },
  {
    id: 'src-current-tools-750',
    publisher: 'Current Tools',
    manufacturerId: 'mfr-current-tools',
    title: 'Model 750 Mechanical Bender manual',
    url: 'https://currenttools.com/images/pdf/manuals/new_manuals_with_disclaimer_2020/750_manual.pdf',
    sourceType: 'official_pdf_manual',
    retrievalDate: DATE,
    publicationOrRevisionDate: '06/11 REV. 4',
    region: 'US',
    currency: 'current',
    modelsCovered: ['750'],
    pageTableOrSection: 'Capacity / operating instructions',
    excerpt: '1/2 to 1 Rigid/IMC and schedule 40 — not EMT-focused',
    accessNotes: 'Primarily Rigid/IMC; EMT support not claimed in capacity header.',
    redistributionLicenseStatus: 'url_reference_only',
    contentChecksum: null,
  },
  {
    id: 'src-current-tools-77',
    publisher: 'Current Tools',
    manufacturerId: 'mfr-current-tools',
    title: '77 Series Electric Bender manual',
    url: 'https://currenttools.com/images/pdf/manuals/77-series-electric-bender.pdf',
    sourceType: 'official_pdf_manual',
    retrievalDate: DATE,
    publicationOrRevisionDate: null,
    region: 'US',
    currency: 'current',
    modelsCovered: ['77', '77-EMT', '77-RIG', '77-IMC', '77-PVC', '700E'],
    pageTableOrSection: 'Stub-Up Bending Information pages 20-23',
    excerpt: 'Electric bender 1/2 thru 2 EMT/RIGID/IMC with stub-up charts',
    accessNotes: 'Extract numeric stub charts carefully before promoting EMT deducts.',
    redistributionLicenseStatus: 'url_reference_only',
    contentChecksum: null,
  },
  {
    id: 'src-rack-hoppy',
    publisher: 'Rack-A-Tiers',
    manufacturerId: 'mfr-rack-a-tiers',
    title: 'Hoppy Bender product page',
    url: 'https://rack-a-tiers.com/product/hoppy-bender/',
    sourceType: 'official_product_page',
    retrievalDate: DATE,
    publicationOrRevisionDate: null,
    region: 'US',
    currency: 'current',
    modelsCovered: ['Hoppy Bender'],
    pageTableOrSection: 'Features',
    excerpt: 'Stop for repeatable bends; multipliers engraved; no stub-up chart',
    accessNotes: 'Identity/feature reference only.',
    redistributionLicenseStatus: 'url_reference_only',
    contentChecksum: null,
  },
  {
    id: 'src-rack-skybender',
    publisher: 'Rack-A-Tiers',
    manufacturerId: 'mfr-rack-a-tiers',
    title: 'Skybender Lift Mounted EMT Bender',
    url: 'https://rack-a-tiers.com/product/skybender-lift-mounted-emt-bender/',
    sourceType: 'official_product_page',
    retrievalDate: DATE,
    publicationOrRevisionDate: null,
    region: 'US',
    currency: 'current',
    modelsCovered: ['Skybender'],
    pageTableOrSection: 'Product features',
    excerpt: 'Bends EMT 1/2 3/4 1 with angle demarcations; no take-up chart',
    accessNotes: 'Identity/capacity only.',
    redistributionLicenseStatus: 'url_reference_only',
    contentChecksum: null,
  },
  {
    id: 'src-benfield-manual-lead',
    publisher: 'ECM / Benfield literature',
    manufacturerId: 'mfr-benfield',
    title: 'Benfield Conduit Bending Manual (trade instructional)',
    url: 'https://store.ecmweb.com/benfield-conduit-bending-manual-2nd-edition',
    sourceType: 'secondary_technical',
    retrievalDate: DATE,
    publicationOrRevisionDate: '2nd edition (store listing)',
    region: 'US',
    currency: 'unknown',
    modelsCovered: [],
    pageTableOrSection: null,
    excerpt: 'Instructional bending manual — not a model-specific OEM chart',
    accessNotes: 'Lead only — never sole source for numerical production values.',
    redistributionLicenseStatus: 'url_reference_only',
    contentChecksum: null,
  },
  {
    id: 'src-ridgid-e666-distributor',
    publisher: 'RIDGID distributor listing',
    manufacturerId: 'mfr-ridgid',
    title: 'E-666 Electric Bender distributor feature sheet',
    url: 'https://www.rac-kettering-ridgid-tool-uk-distributor.co.uk/48_tubing_bender.html',
    sourceType: 'retailer_listing',
    retrievalDate: DATE,
    publicationOrRevisionDate: null,
    region: 'UK',
    currency: 'unknown',
    modelsCovered: ['E-666', 'E-665TL-90'],
    pageTableOrSection: 'Features',
    excerpt: 'Claims 1/2 to 2 Rigid IMC EMT; chart mentioned but not transcribed',
    accessNotes: 'Distributor lead only — locate RIDGID official manual before any numeric facts.',
    redistributionLicenseStatus: 'url_reference_only',
    contentChecksum: null,
  },
];

/** @type {any[]} */
const models = [];
/** @type {any[]} */
const measurements = [];
/** @type {any[]} */
const conflicts = [];

function addModel(m) {
  models.push({
    introducedDate: null,
    discontinuedDate: null,
    replacementModelIds: [],
    parentFrameModelId: null,
    operationMode: m.category === 'hand' ? 'hand_continuous' : m.operationMode ?? null,
    ...m,
  });
}

function addFact(f) {
  const normalized =
    f.normalizedValueInches === undefined
      ? f.originalValue === null || f.originalUnit === 'none' || f.originalUnit === 'degree'
        ? null
        : typeof f.originalValue === 'number'
          ? f.originalValue
          : frac(f.originalValue)
      : f.normalizedValueInches;
  measurements.push({
    accessoryOrShoeId: null,
    operation: null,
    page: null,
    section: null,
    table: null,
    excerpt: null,
    conflictGroupId: null,
    notes: '',
    productionScope: 'emt_in_scope',
    ...f,
    normalizedValueInches: normalized,
  });
}

// --- Greenlee Site-Rite hand families (production mirror + expansion) ---
const greenleeAl = [
  ['840A', '840AH', '1/2', '5', '4-3/16'],
  ['841A', '841AH', '3/4', '6', '5-1/8'],
  ['842A', '842AH', '1', '8', '6-1/2'],
  ['843A', '843AH', '1-1/4', '11', '9-5/8'],
];
for (const [head, withHandle, size, deduct, radius] of greenleeAl) {
  const id = `model-greenlee-${head.toLowerCase()}`;
  addModel({
    id,
    manufacturerId: 'mfr-greenlee',
    brand: 'Greenlee',
    family: 'Site-Rite',
    series: 'Site-Rite aluminum single-shoe hand bender',
    modelNumbers: [head, withHandle],
    skus: [head, withHandle],
    aliases: [],
    category: 'hand',
    driveType: 'manual',
    material: 'aluminum',
    marketStatus: 'active',
    regions: ['US'],
    supportedConduitTypes: size === '1/2' ? ['EMT'] : ['EMT', 'IMC', 'RMC'],
    supportedNominalSizes: [size],
    sourceIds: ['src-greenlee-site-rite-cdn', 'src-greenlee-site-rite-manualsnet-mirror'],
    notes: `${withHandle} includes handle. Capacity notes vary by size for Rigid/IMC.`,
    researchClass: 'chart_candidate',
  });
  addFact({
    id: `fact-${head.toLowerCase()}-emt-${size.replace('/', '_')}-deduct`,
    modelId: id,
    conduitType: 'EMT',
    nominalSize: size,
    property: 'stub_deduct',
    originalLabel: 'DEDUCT (in.)',
    originalValue: Number(deduct),
    originalUnit: 'inch',
    sourceId: 'src-greenlee-site-rite-cdn',
    table: 'Specifications MODEL CATALOG # BEND RADIUS / DEDUCT',
    excerpt: `${head} deduct ${deduct}`,
    evidenceStatus: 'official_corroborated',
    confidence: 'high',
  });
  addFact({
    id: `fact-${head.toLowerCase()}-emt-${size.replace('/', '_')}-clr`,
    modelId: id,
    conduitType: 'EMT',
    nominalSize: size,
    property: 'centerline_radius',
    originalLabel: 'BEND RADIUS (in.)',
    originalValue: radius,
    originalUnit: 'inch',
    sourceId: 'src-greenlee-site-rite-cdn',
    table: 'Specifications MODEL CATALOG # BEND RADIUS / DEDUCT',
    excerpt: `${head} bend radius ${radius}`,
    evidenceStatus: 'official_corroborated',
    confidence: 'high',
  });
}

const greenleeIron = [
  ['840F', '840FH', '1/2', '5', '4-3/16'],
  ['841F', '841FH', '3/4', '6', '5-1/8'],
  ['842F', '842FH', '1', '8', '6-1/2'],
  ['843F', '843FH', '1-1/4', '11', '9-5/8'],
];
for (const [head, withHandle, size, deduct, radius] of greenleeIron) {
  const id = `model-greenlee-${head.toLowerCase()}`;
  addModel({
    id,
    manufacturerId: 'mfr-greenlee',
    brand: 'Greenlee',
    family: 'Site-Rite',
    series: 'Site-Rite iron single-shoe hand bender',
    modelNumbers: [head, withHandle],
    skus: [head, withHandle],
    aliases: [],
    category: 'hand',
    driveType: 'manual',
    material: 'iron',
    marketStatus: 'active',
    regions: ['US'],
    supportedConduitTypes: ['EMT', 'IMC', 'RMC'],
    supportedNominalSizes: [size],
    sourceIds: ['src-greenlee-site-rite-cdn', 'src-greenlee-site-rite-manualsnet-mirror'],
    notes: `${withHandle} includes handle.`,
    researchClass: 'chart_candidate',
  });
  addFact({
    id: `fact-${head.toLowerCase()}-emt-${size.replace('/', '_')}-deduct`,
    modelId: id,
    conduitType: 'EMT',
    nominalSize: size,
    property: 'stub_deduct',
    originalLabel: 'DEDUCT (in.)',
    originalValue: Number(deduct),
    originalUnit: 'inch',
    sourceId: 'src-greenlee-site-rite-cdn',
    table: 'Specifications',
    excerpt: `${head} deduct ${deduct}`,
    evidenceStatus: 'official_corroborated',
    confidence: 'high',
  });
  addFact({
    id: `fact-${head.toLowerCase()}-emt-${size.replace('/', '_')}-clr`,
    modelId: id,
    conduitType: 'EMT',
    nominalSize: size,
    property: 'centerline_radius',
    originalLabel: 'BEND RADIUS (in.)',
    originalValue: radius,
    originalUnit: 'inch',
    sourceId: 'src-greenlee-site-rite-cdn',
    table: 'Specifications',
    excerpt: `${head} bend radius ${radius}`,
    evidenceStatus: 'official_corroborated',
    confidence: 'high',
  });
}

addModel({
  id: 'model-greenlee-844a',
  manufacturerId: 'mfr-greenlee',
  brand: 'Greenlee',
  family: 'Site-Rite',
  series: 'Site-Rite dual-shoe hand bender',
  modelNumbers: ['844A', '844AH'],
  skus: ['844A', '844AH'],
  aliases: ['Site-Rite dual shoe'],
  category: 'hand',
  driveType: 'manual',
  material: 'aluminum dual-shoe',
  marketStatus: 'active',
  regions: ['US'],
  supportedConduitTypes: ['EMT', 'IMC', 'RMC'],
  supportedNominalSizes: ['1/2', '3/4'],
  sourceIds: ['src-greenlee-site-rite-cdn', 'src-greenlee-site-rite-manualsnet-mirror'],
  notes: 'Dual-shoe: values apply per groove/size. Do not bend two conduits at once.',
  researchClass: 'chart_candidate',
});
for (const [size, deduct, radius] of [
  ['1/2', 5, '4-3/16'],
  ['3/4', 6, '5-1/8'],
]) {
  addFact({
    id: `fact-844a-emt-${size.replace('/', '_')}-deduct`,
    modelId: 'model-greenlee-844a',
    conduitType: 'EMT',
    nominalSize: size,
    property: 'stub_deduct',
    originalLabel: 'DEDUCT (in.)',
    originalValue: deduct,
    originalUnit: 'inch',
    sourceId: 'src-greenlee-site-rite-cdn',
    table: 'ALUMINUM DUAL SHOE 844A/AH',
    excerpt: `844A ${size} groove deduct ${deduct}`,
    evidenceStatus: 'official_corroborated',
    confidence: 'high',
    notes: 'Per-groove values on dual-shoe head.',
  });
  addFact({
    id: `fact-844a-emt-${size.replace('/', '_')}-clr`,
    modelId: 'model-greenlee-844a',
    conduitType: 'EMT',
    nominalSize: size,
    property: 'centerline_radius',
    originalLabel: 'BEND RADIUS (in.)',
    originalValue: radius,
    originalUnit: 'inch',
    sourceId: 'src-greenlee-site-rite-cdn',
    table: 'ALUMINUM DUAL SHOE 844A/AH',
    excerpt: `844A ${size} groove radius ${radius}`,
    evidenceStatus: 'official_corroborated',
    confidence: 'high',
  });
}

// Klein Angle Setter — SKU-level
const klein = [
  ['51608', '51603', 'iron', '1/2', 5, 4.625, 'src-klein-51608'],
  ['51609', '51604', 'iron', '3/4', 6, 5.5, 'src-klein-51604'],
  ['51610', '51605', 'iron', '1', 8, 7.375, 'src-klein-51610'],
  ['51606', '51606', 'aluminum', '1/2', 5, 4.625, 'src-klein-51606'],
  ['51607', '51607', 'aluminum', '3/4', 6, 5.5, 'src-klein-51607'],
];
for (const [head, assembly, material, size, stub, clr, src] of klein) {
  const id = `model-klein-${head}`;
  addModel({
    id,
    manufacturerId: 'mfr-klein',
    brand: 'Klein Tools',
    family: 'Angle Setter',
    series: 'Angle Setter hand bender',
    modelNumbers: head === assembly ? [head] : [head, assembly],
    skus: head === assembly ? [head] : [head, assembly],
    aliases: assembly !== head ? [`full assembly ${assembly}`] : [],
    category: 'hand',
    driveType: 'manual',
    material,
    marketStatus: 'active',
    regions: ['US'],
    supportedConduitTypes: ['EMT'],
    supportedNominalSizes: [size],
    sourceIds: [src],
    notes: 'Manufacturer label Stub-Up Height treated as stub take-up/deduct for marking.',
    researchClass: 'chart_candidate',
  });
  addFact({
    id: `fact-klein-${head}-stub`,
    modelId: id,
    conduitType: 'EMT',
    nominalSize: size,
    property: 'stub_take_up',
    originalLabel: 'Stub-Up Height (Inch)',
    originalValue: stub,
    originalUnit: 'inch',
    sourceId: src,
    section: 'Specifications',
    excerpt: `Stub-Up Height ${stub}`,
    evidenceStatus: 'official_exact',
    confidence: 'high',
  });
  addFact({
    id: `fact-klein-${head}-clr`,
    modelId: id,
    conduitType: 'EMT',
    nominalSize: size,
    property: 'centerline_radius',
    originalLabel: 'Centerline Bend Radius (Inch)',
    originalValue: clr,
    originalUnit: 'inch',
    sourceId: src,
    section: 'Specifications',
    excerpt: `Centerline Bend Radius ${clr}`,
    evidenceStatus: 'official_exact',
    confidence: 'high',
  });
}

// Gardner BigBen
for (const [sku, size, deduct, radius] of [
  ['960', '1/2', 5, 3.69],
  ['961', '3/4', 6, 4.74],
  ['962', '1', 8, 5.81],
]) {
  const id = `model-gardner-${sku}`;
  addModel({
    id,
    manufacturerId: 'mfr-gardner-bender',
    brand: 'Gardner Bender',
    family: 'BigBen',
    series: 'BigBen aluminum hand bender',
    modelNumbers: [sku, `${sku}H`],
    skus: [sku, `${sku}H`],
    aliases: [],
    category: 'hand',
    driveType: 'manual',
    material: 'aluminum',
    marketStatus: 'active',
    regions: ['US'],
    supportedConduitTypes: ['EMT', 'IMC', 'RMC'],
    supportedNominalSizes: [size],
    sourceIds: ['src-gardner-howto-gar-bro-032', 'src-gardner-npa-759-bigben'],
    notes: 'H suffix = head+handle. Older B-0040 mislabels deduct as radius — rejected.',
    researchClass: 'chart_candidate',
  });
  addFact({
    id: `fact-gardner-${sku}-deduct`,
    modelId: id,
    conduitType: 'EMT',
    nominalSize: size,
    property: 'stub_deduct',
    originalLabel: 'EMT Deduct',
    originalValue: deduct,
    originalUnit: 'inch',
    sourceId: 'src-gardner-howto-gar-bro-032',
    table: 'Table 1',
    excerpt: `EMT deduct ${deduct} for ${size}`,
    evidenceStatus: 'official_corroborated',
    confidence: 'high',
  });
  addFact({
    id: `fact-gardner-${sku}-clr`,
    modelId: id,
    conduitType: 'EMT',
    nominalSize: size,
    property: 'centerline_radius',
    originalLabel: 'Radius',
    originalValue: radius,
    originalUnit: 'inch',
    sourceId: 'src-gardner-howto-gar-bro-032',
    table: 'Aluminum BigBen Hand Bender',
    excerpt: `${sku} radius ${radius}`,
    evidenceStatus: 'official_corroborated',
    confidence: 'high',
  });
}

// Rejected Gardner B-0040 mislabel — as rejected measurement placeholders tied to notes
addFact({
  id: 'fact-gardner-b0040-rejected-radius-mislabeled',
  modelId: 'model-gardner-960',
  conduitType: 'EMT',
  nominalSize: '1/2',
  property: 'centerline_radius',
  originalLabel: 'radius (mislabel of deduct on B-0040)',
  originalValue: 5,
  originalUnit: 'inch',
  sourceId: 'src-gardner-b0040-legacy-mislabeled',
  evidenceStatus: 'rejected',
  confidence: 'none',
  notes:
    'Older Gardner B-0040 guide mislabels deduct values (5/6/8) as radius. Rejected; do not use. Conflict documented vs current How To Guide radii.',
  productionScope: 'n/a',
  conflictGroupId: 'conflict-gardner-radius-mislabeled',
});

conflicts.push({
  id: 'conflict-gardner-radius-mislabeled',
  modelId: 'model-gardner-960',
  property: 'centerline_radius',
  nominalSize: '1/2',
  competingFactIds: ['fact-gardner-960-clr', 'fact-gardner-b0040-rejected-radius-mislabeled'],
  conflictType: 'revision_change',
  analysis:
    'Legacy B-0040 printed deduct numbers in a radius column. Current How To Guide + NPA-759 publish true radii 3.69/4.74/5.81. Production already warns about this.',
  recommendedNextStep: 'Keep rejected legacy fact visible; never promote B-0040 radius values.',
  status: 'needs_human_review',
});

// IDEAL
for (const [sku, material, size, stub, src] of [
  ['74-031', 'aluminum', '1/2', 5, 'src-ideal-74-031'],
  ['74-032', 'aluminum', '3/4', 6, 'src-ideal-74-032'],
  ['74-001', 'ductile iron', '1/2', 5, 'src-ideal-74-001'],
  ['74-002', 'ductile iron', '3/4', 6, 'src-ideal-74-002'],
]) {
  const id = `model-ideal-${sku}`;
  addModel({
    id,
    manufacturerId: 'mfr-ideal',
    brand: 'IDEAL',
    family: 'IDEAL hand bender',
    series: material.includes('aluminum') ? 'Aluminum hand bender' : 'Ductile iron hand bender',
    modelNumbers: [sku],
    skus: [sku],
    aliases: [],
    category: 'hand',
    driveType: 'manual',
    material,
    marketStatus: 'active',
    regions: ['US', 'CA'],
    supportedConduitTypes: ['EMT'],
    supportedNominalSizes: [size],
    sourceIds: [src],
    notes: 'Stub Up Height published; no official centerline radius on product pages reviewed.',
    researchClass: 'chart_candidate',
  });
  addFact({
    id: `fact-ideal-${sku}-stub`,
    modelId: id,
    conduitType: 'EMT',
    nominalSize: size,
    property: 'stub_take_up',
    originalLabel: 'Stub Up Height',
    originalValue: stub,
    originalUnit: 'inch',
    sourceId: src,
    section: 'Key Specifications',
    excerpt: `Stub Up Height ${stub}`,
    evidenceStatus: 'official_exact',
    confidence: 'high',
  });
}

addModel({
  id: 'model-ideal-74-003',
  manufacturerId: 'mfr-ideal',
  brand: 'IDEAL',
  family: 'IDEAL hand bender',
  series: 'Ductile iron hand bender',
  modelNumbers: ['74-003'],
  skus: ['74-003'],
  aliases: [],
  category: 'hand',
  driveType: 'manual',
  material: 'ductile iron',
  marketStatus: 'active',
  regions: ['US'],
  supportedConduitTypes: ['EMT'],
  supportedNominalSizes: ['1'],
  sourceIds: ['src-ideal-74-003'],
  notes: 'Production lists stub-up 8; re-confirm live page stub-up before promoting.',
  researchClass: 'reference_only',
});
addFact({
  id: 'fact-ideal-74-003-stub-prod-mirror',
  modelId: 'model-ideal-74-003',
  conduitType: 'EMT',
  nominalSize: '1',
  property: 'stub_take_up',
  originalLabel: 'Stub Up Height (production workbook mirror)',
  originalValue: 8,
  originalUnit: 'inch',
  sourceId: 'src-ideal-74-003',
  evidenceStatus: 'secondary_only',
  confidence: 'medium',
  notes: 'Mirrored from Bend Pro production profile pending live page stub-up re-read.',
  productionScope: 'emt_in_scope',
});

addModel({
  id: 'model-ideal-74-034',
  manufacturerId: 'mfr-ideal',
  brand: 'IDEAL',
  family: 'IDEAL hand bender',
  series: 'Ductile iron hand bender',
  modelNumbers: ['74-034'],
  skus: ['74-034'],
  aliases: ['74-006 head may be related'],
  category: 'hand',
  driveType: 'manual',
  material: 'ductile iron',
  marketStatus: 'unknown',
  regions: ['US'],
  supportedConduitTypes: ['EMT'],
  supportedNominalSizes: ['1-1/4'],
  sourceIds: ['src-ideal-74-034'],
  notes: 'Related catalog also lists 74-006 as 1-1/4 EMT head — SKU relationship needs human confirmation.',
  researchClass: 'conflict_review',
});
addFact({
  id: 'fact-ideal-74-034-stub-prod-mirror',
  modelId: 'model-ideal-74-034',
  conduitType: 'EMT',
  nominalSize: '1-1/4',
  property: 'stub_take_up',
  originalLabel: 'Stub Up Height (production workbook mirror)',
  originalValue: 11,
  originalUnit: 'inch',
  sourceId: 'src-ideal-74-034',
  evidenceStatus: 'secondary_only',
  confidence: 'medium',
  notes: 'Pending live confirmation; possible related SKU 74-006.',
  conflictGroupId: 'conflict-ideal-114-sku',
});

conflicts.push({
  id: 'conflict-ideal-114-sku',
  modelId: 'model-ideal-74-034',
  property: 'stub_take_up',
  nominalSize: '1-1/4',
  competingFactIds: ['fact-ideal-74-034-stub-prod-mirror', 'fact-ideal-74-034-stub-prod-mirror'],
  conflictType: 'model_generation_ambiguity',
  analysis:
    'Production cites 74-034 assembly for 1-1/4 EMT stub-up 11. Related-product navigation also surfaces 74-006 as ductile iron 1-1/4 EMT head. Need official confirmation which SKU owns the chart value.',
  recommendedNextStep: 'Open both live product pages and capture Stub Up Height + configuration (head vs head+handle).',
  status: 'open',
});

// Milwaukee + Southwire identity
for (const [sku, material, size] of [
  ['48-22-4070', 'aluminum', '1/2'],
  ['48-22-4071', 'aluminum', '3/4'],
  ['48-22-4072', 'aluminum', '1'],
  ['48-22-4080', 'ductile iron', '1/2'],
  ['48-22-4081', 'ductile iron', '3/4'],
  ['48-22-4082', 'ductile iron', '1'],
]) {
  addModel({
    id: `model-milwaukee-${sku}`,
    manufacturerId: 'mfr-milwaukee',
    brand: 'Milwaukee',
    family: 'Hand bender',
    series: 'Hand bender',
    modelNumbers: [sku],
    skus: [sku],
    aliases: [],
    category: 'hand',
    driveType: 'manual',
    material,
    marketStatus: 'active',
    regions: ['US'],
    supportedConduitTypes: ['EMT'],
    supportedNominalSizes: [size],
    sourceIds: [`src-milwaukee-${sku}`],
    notes: 'No published stub-up or radius on official product page reviewed 2026-07-14.',
    researchClass: 'reference_only',
  });
}

for (const [model, sku, size, material] of [
  ['MCB1/2', '58281340', '1/2', 'aluminum'],
  ['MCB3/4', '58281240', '3/4', 'aluminum'],
  ['MCB1', '58281440', '1', 'ductile iron'],
]) {
  addModel({
    id: `model-southwire-${model.toLowerCase().replace('/', '-')}`,
    manufacturerId: 'mfr-southwire',
    brand: 'Southwire',
    family: 'MCB',
    series: 'Conduit hand bender',
    modelNumbers: [model],
    skus: [sku],
    aliases: [],
    category: 'hand',
    driveType: 'manual',
    material,
    marketStatus: 'active',
    regions: ['US'],
    supportedConduitTypes: ['EMT'],
    supportedNominalSizes: [size],
    sourceIds: ['src-southwire-2024-hand-benders'],
    notes: 'Cutsheet access flaky (HTTP 400); identity from production + URL retained.',
    researchClass: 'reference_only',
  });
}

// Rack-A-Tiers
addModel({
  id: 'model-rack-hoppy',
  manufacturerId: 'mfr-rack-a-tiers',
  brand: 'Rack-A-Tiers',
  family: 'Hoppy Bender',
  series: 'Hoppy Bender',
  modelNumbers: ['Hoppy Bender'],
  skus: [],
  aliases: [],
  category: 'hand',
  driveType: 'manual',
  material: null,
  marketStatus: 'active',
  regions: ['US', 'CA'],
  supportedConduitTypes: ['EMT'],
  supportedNominalSizes: ['1/2', '3/4'],
  sourceIds: ['src-rack-hoppy'],
  notes: 'Official page describes stop/multipliers; no stub-up/radius chart published.',
  researchClass: 'reference_only',
});
addModel({
  id: 'model-rack-skybender',
  manufacturerId: 'mfr-rack-a-tiers',
  brand: 'Rack-A-Tiers',
  family: 'Skybender',
  series: 'Lift-mounted EMT bender',
  modelNumbers: ['Skybender'],
  skus: [],
  aliases: [],
  category: 'mechanical',
  driveType: 'manual',
  material: null,
  marketStatus: 'active',
  regions: ['US', 'CA'],
  supportedConduitTypes: ['EMT', 'aluminum_rigid'],
  supportedNominalSizes: ['1/2', '3/4', '1'],
  sourceIds: ['src-rack-skybender'],
  notes: 'Stationary lift-mounted; identity/capacity only.',
  researchClass: 'reference_only',
  operationMode: 'hand_continuous',
});

// Greenlee 555 electric frame + EMT shoe group
addModel({
  id: 'model-greenlee-555c',
  manufacturerId: 'mfr-greenlee',
  brand: 'Greenlee',
  family: '555',
  series: '555 Series electric conduit bender',
  modelNumbers: ['555C', '555CX', '555DX'],
  skus: ['555C', '555CX', '555DX'],
  aliases: ['Triple Nickel'],
  category: 'electric',
  driveType: 'electric',
  material: null,
  marketStatus: 'active',
  regions: ['US'],
  supportedConduitTypes: ['EMT', 'IMC', 'RMC'],
  supportedNominalSizes: ['1/2', '3/4', '1', '1-1/4', '1-1/2', '2'],
  sourceIds: ['src-greenlee-555-single-shoe-52065584-rev02', 'src-greenlee-2015-bending-catalog'],
  notes: 'Frame/power unit — chart values belong to shoe groups.',
  researchClass: 'identity_verified',
  operationMode: 'one_shot',
});
addModel({
  id: 'model-greenlee-shoe-23803',
  manufacturerId: 'mfr-greenlee',
  brand: 'Greenlee',
  family: '555',
  series: '555 EMT single shoe group',
  modelNumbers: ['23803'],
  skus: ['23803'],
  aliases: ['EMT Shoe Group 1/2-2'],
  category: 'shoe',
  driveType: 'n/a',
  material: null,
  marketStatus: 'active',
  regions: ['US'],
  supportedConduitTypes: ['EMT'],
  supportedNominalSizes: ['1/2', '3/4', '1', '1-1/4', '1-1/2', '2'],
  sourceIds: ['src-greenlee-555-single-shoe-52065584-rev02', 'src-greenlee-23803-product'],
  notes: 'Compatible with 555C per product page. CLR conflict between product page and REV02 manual.',
  researchClass: 'conflict_review',
  parentFrameModelId: 'model-greenlee-555c',
  operationMode: 'one_shot',
});

const greenlee555EmtClrManual = [
  ['1/2', '4-5/16'],
  ['3/4', '5-1/2'],
  ['1', '7'],
  ['1-1/4', '8-13/16'],
  ['1-1/2', '8-3/8'],
  ['2', '9-1/4'],
];
const greenlee555EmtClrPage = [
  ['1/2', '4-1/4'],
  ['3/4', '5-7/16'],
  ['1', '6-15/16'],
  ['1-1/4', '8-3/4'],
  ['1-1/2', '8-1/4'],
  ['2', '9'],
];
const greenlee555EmtDeduct = [
  ['1/2', '7-1/2'],
  ['3/4', '9'],
  ['1', '11'],
  ['1-1/4', '13-5/8'],
  ['1-1/2', '14-7/8'],
  ['2', '16-3/8'],
];

for (const [size, val] of greenlee555EmtClrManual) {
  addFact({
    id: `fact-23803-emt-${size.replace('/', '_')}-clr-manual`,
    modelId: 'model-greenlee-shoe-23803',
    conduitType: 'EMT',
    nominalSize: size,
    property: 'centerline_radius',
    originalLabel: 'Centerline Bending Radii — EMT',
    originalValue: val,
    originalUnit: 'inch',
    sourceId: 'src-greenlee-555-single-shoe-52065584-rev02',
    table: 'Centerline Bending Radii for EMT, IMC, and Rigid Shoe Groups',
    excerpt: `EMT ${size} CLR ${val}`,
    evidenceStatus: 'official_conflict',
    confidence: 'high',
    conflictGroupId: `conflict-23803-clr-${size.replace('/', '_')}`,
    notes: 'From official single-shoe manual EMT column.',
  });
}
for (const [size, val] of greenlee555EmtClrPage) {
  addFact({
    id: `fact-23803-emt-${size.replace('/', '_')}-clr-page`,
    modelId: 'model-greenlee-shoe-23803',
    conduitType: 'EMT',
    nominalSize: size,
    property: 'centerline_radius',
    originalLabel: 'Centerline Bend Radius (product page)',
    originalValue: val,
    originalUnit: 'inch',
    sourceId: 'src-greenlee-23803-product',
    section: 'Specifications',
    excerpt: `Product page lists ${size} ${val}`,
    evidenceStatus: 'official_conflict',
    confidence: 'medium',
    conflictGroupId: `conflict-23803-clr-${size.replace('/', '_')}`,
    notes: 'Matches Rigid/IMC column of REV02 — likely page labeling error.',
  });
  conflicts.push({
    id: `conflict-23803-clr-${size.replace('/', '_')}`,
    modelId: 'model-greenlee-shoe-23803',
    property: 'centerline_radius',
    nominalSize: size,
    competingFactIds: [
      `fact-23803-emt-${size.replace('/', '_')}-clr-manual`,
      `fact-23803-emt-${size.replace('/', '_')}-clr-page`,
    ],
    conflictType: 'value_mismatch',
    analysis:
      'Official product page CLR for EMT shoe 23803 matches the Rigid/IMC column of 52065584REV02, not the EMT column. Manual is preferred pending Greenlee confirmation.',
    recommendedNextStep: 'Ask Greenlee which document is authoritative for 23803 EMT CLR; keep both facts.',
    status: 'open',
  });
}
for (const [size, val] of greenlee555EmtDeduct) {
  addFact({
    id: `fact-23803-emt-${size.replace('/', '_')}-deduct`,
    modelId: 'model-greenlee-shoe-23803',
    conduitType: 'EMT',
    nominalSize: size,
    property: 'stub_deduct',
    originalLabel: 'DEDUCT — EMT',
    originalValue: val,
    originalUnit: 'inch',
    sourceId: 'src-greenlee-555-single-shoe-52065584-rev02',
    table: 'Deduct Table for EMT, IMC, and Rigid Shoe Groups',
    excerpt: `EMT ${size} deduct ${val}; min stub = deduct + 2`,
    evidenceStatus: 'official_exact',
    confidence: 'medium',
    notes: 'Manual states figures are approximate. Electric shoe deduct — NOT hand-bender 5/6/8/11.',
  });
  addFact({
    id: `fact-23803-emt-${size.replace('/', '_')}-minstub`,
    modelId: 'model-greenlee-shoe-23803',
    conduitType: 'EMT',
    nominalSize: size,
    property: 'minimum_stub',
    originalLabel: 'MINIMUM STUB LENGTH = DEDUCT PLUS 2 INCHES',
    originalValue: frac(val) + 2,
    originalUnit: 'inch',
    sourceId: 'src-greenlee-555-single-shoe-52065584-rev02',
    table: 'Deduct Table',
    excerpt: 'Minimum stub length = deduct plus 2 inches',
    evidenceStatus: 'official_exact',
    confidence: 'medium',
    notes: 'Derived only from explicit manual formula deduct+2, not inferred geometry.',
  });
}

// Gardner B2555
addModel({
  id: 'model-gardner-b2555',
  manufacturerId: 'mfr-gardner-bender',
  brand: 'Gardner Bender',
  family: 'Sidewinder',
  series: 'B2555 Electric Sidewinder',
  modelNumbers: ['B2555', 'B2555EMT', 'B2555RIG', 'B2555IMC', 'B2555PVC'],
  skus: ['B2555', 'B2555EMT', 'B2555RIG', 'B2555IMC', 'B2555PVC'],
  aliases: ['Sidewinder'],
  category: 'electric',
  driveType: 'electric',
  material: null,
  marketStatus: 'active',
  regions: ['US'],
  supportedConduitTypes: ['EMT', 'IMC', 'RMC'],
  supportedNominalSizes: ['1/2', '3/4', '1', '1-1/4', '1-1/2', '2'],
  sourceIds: ['src-gardner-b2555-is-002', 'src-gardner-b2555-product'],
  notes: 'Shoes interchange with Greenlee 555 PL/AAJ per IS_002.',
  researchClass: 'chart_candidate',
  operationMode: 'one_shot',
});
addModel({
  id: 'model-gardner-bemt-52',
  manufacturerId: 'mfr-gardner-bender',
  brand: 'Gardner Bender',
  family: 'Sidewinder',
  series: 'B2555 EMT shoe group',
  modelNumbers: ['BEMT-52'],
  skus: ['BEMT-52'],
  aliases: [],
  category: 'shoe',
  driveType: 'n/a',
  material: null,
  marketStatus: 'active',
  regions: ['US'],
  supportedConduitTypes: ['EMT'],
  supportedNominalSizes: ['1/2', '3/4', '1', '1-1/4', '1-1/2', '2'],
  sourceIds: ['src-gardner-b2555-is-002'],
  notes: 'EMT shoe/support kit for B2555.',
  researchClass: 'chart_candidate',
  parentFrameModelId: 'model-gardner-b2555',
  operationMode: 'one_shot',
});

const b2555EmtDeduct = [
  ['1/2', '7'],
  ['3/4', '8-7/8'],
  ['1', '10-3/4'],
  ['1-1/4', '13-1/8'],
  ['1-1/2', '13-7/8'],
  ['2', '15-3/8'],
];
for (const [size, val] of b2555EmtDeduct) {
  addFact({
    id: `fact-bemt52-emt-${size.replace('/', '_')}-deduct`,
    modelId: 'model-gardner-bemt-52',
    conduitType: 'EMT',
    nominalSize: size,
    property: 'stub_deduct',
    originalLabel: 'Deduct Length',
    originalValue: val,
    originalUnit: 'inch',
    sourceId: 'src-gardner-b2555-is-002',
    table: 'Chart B – EMT Conduit',
    excerpt: `EMT ${size} deduct ${val}`,
    evidenceStatus: 'official_exact',
    confidence: 'high',
    notes: 'Electric shoe deduct; distinct from hand BigBen 5/6/8.',
  });
}
const b2555EmtClr = [
  ['1/2', '4-1/4'],
  ['3/4', '5-3/8'],
  ['1', '6-3/4'],
  ['1-1/4', '8-3/4'],
  ['1-1/2', '8-9/32'],
  ['2', '9-3/16'],
];
for (const [size, val] of b2555EmtClr) {
  addFact({
    id: `fact-bemt52-emt-${size.replace('/', '_')}-clr`,
    modelId: 'model-gardner-bemt-52',
    conduitType: 'EMT',
    nominalSize: size,
    property: 'centerline_radius',
    originalLabel: 'EMT bending radius',
    originalValue: val,
    originalUnit: 'inch',
    sourceId: 'src-gardner-b2555-is-002',
    table: 'Bending radius table',
    excerpt: `EMT ${size} radius ${val}`,
    evidenceStatus: 'official_exact',
    confidence: 'high',
  });
}

// Current Tools
addModel({
  id: 'model-current-254',
  manufacturerId: 'mfr-current-tools',
  brand: 'Current Tools',
  family: '254',
  series: 'Hydraulic conduit bender',
  modelNumbers: ['254'],
  skus: ['254'],
  aliases: [],
  category: 'hydraulic',
  driveType: 'hydraulic',
  material: null,
  marketStatus: 'active',
  regions: ['US'],
  supportedConduitTypes: ['EMT', 'IMC', 'RMC'],
  supportedNominalSizes: ['2-1/2', '3', '3-1/2', '4'],
  sourceIds: ['src-current-tools-254'],
  notes: 'One-shot hydraulic; shoe kits per size. Outside typical hand-bender EMT range.',
  researchClass: 'chart_candidate',
  operationMode: 'one_shot',
});
for (const [size, shoe] of [
  ['2-1/2', '254-111'],
  ['3', '254-118'],
  ['3-1/2', '254-125'],
  ['4', '254-132'],
]) {
  addModel({
    id: `model-current-${shoe}`,
    manufacturerId: 'mfr-current-tools',
    brand: 'Current Tools',
    family: '254',
    series: '254 bending shoe',
    modelNumbers: [shoe],
    skus: [shoe],
    aliases: [],
    category: 'shoe',
    driveType: 'n/a',
    material: null,
    marketStatus: 'active',
    regions: ['US'],
    supportedConduitTypes: ['EMT', 'IMC', 'RMC'],
    supportedNominalSizes: [size],
    sourceIds: ['src-current-tools-254'],
    notes: 'Shoe for Model 254 frame.',
    researchClass: 'identity_verified',
    parentFrameModelId: 'model-current-254',
    operationMode: 'one_shot',
  });
}
const ct254Emt = [
  ['2-1/2', '21 1/2', '24', '13 1/2'],
  ['3', '24', '27', '16 1/8'],
  ['3-1/2', '27 3/4', '31 1/4', '18 5/8'],
  ['4', '32 1/4', '36 1/4', '21'],
];
for (const [size, deduct, minStub, clr] of ct254Emt) {
  const shoe =
    size === '2-1/2' ? '254-111' : size === '3' ? '254-118' : size === '3-1/2' ? '254-125' : '254-132';
  const mid = `model-current-${shoe}`;
  const key = size.replace('/', '_').replace(' ', '_');
  addFact({
    id: `fact-ct254-${key}-deduct`,
    modelId: mid,
    conduitType: 'EMT',
    nominalSize: size,
    property: 'stub_deduct',
    originalLabel: 'Deduct Length',
    originalValue: deduct,
    originalUnit: 'inch',
    sourceId: 'src-current-tools-254',
    table: 'Chart B – EMT Conduit',
    excerpt: `EMT ${size} deduct ${deduct}`,
    evidenceStatus: 'official_exact',
    confidence: 'high',
    productionScope: 'out_of_production_scope',
  });
  addFact({
    id: `fact-ct254-${key}-minstub`,
    modelId: mid,
    conduitType: 'EMT',
    nominalSize: size,
    property: 'minimum_stub',
    originalLabel: 'Minimum Stub Length',
    originalValue: minStub,
    originalUnit: 'inch',
    sourceId: 'src-current-tools-254',
    table: 'Chart B – EMT Conduit',
    excerpt: `EMT ${size} min stub ${minStub}`,
    evidenceStatus: 'official_exact',
    confidence: 'high',
    productionScope: 'out_of_production_scope',
  });
  addFact({
    id: `fact-ct254-${key}-clr`,
    modelId: mid,
    conduitType: 'EMT',
    nominalSize: size,
    property: 'centerline_radius',
    originalLabel: 'CONDUIT CENTERLINE BENDING RADII — EMT',
    originalValue: clr,
    originalUnit: 'inch',
    sourceId: 'src-current-tools-254',
    table: 'CONDUIT CENTERLINE BENDING RADII',
    excerpt: `EMT ${size} CLR ${clr}`,
    evidenceStatus: 'official_exact',
    confidence: 'high',
    productionScope: 'out_of_production_scope',
  });
}

addModel({
  id: 'model-current-753',
  manufacturerId: 'mfr-current-tools',
  brand: 'Current Tools',
  family: '753',
  series: 'Mechanical bender',
  modelNumbers: ['753'],
  skus: ['753'],
  aliases: [],
  category: 'mechanical',
  driveType: 'ratchet',
  material: null,
  marketStatus: 'active',
  regions: ['US'],
  supportedConduitTypes: ['EMT', 'IMC', 'RMC'],
  supportedNominalSizes: ['1/2', '3/4', '1', '1-1/4'],
  sourceIds: ['src-current-tools-753'],
  notes: 'Official manual has Chart B EMT deduct — numeric promotion pending careful table re-read.',
  researchClass: 'identity_verified',
  operationMode: 'one_shot',
});
addModel({
  id: 'model-current-750',
  manufacturerId: 'mfr-current-tools',
  brand: 'Current Tools',
  family: '750',
  series: 'Mechanical bender',
  modelNumbers: ['750'],
  skus: ['750'],
  aliases: [],
  category: 'mechanical',
  driveType: 'ratchet',
  material: null,
  marketStatus: 'active',
  regions: ['US'],
  supportedConduitTypes: ['IMC', 'RMC'],
  supportedNominalSizes: ['1/2', '3/4', '1'],
  sourceIds: ['src-current-tools-750'],
  notes: 'Capacity header is Rigid/IMC/schedule 40 — not EMT.',
  researchClass: 'reference_only',
  operationMode: 'one_shot',
});
addModel({
  id: 'model-current-77',
  manufacturerId: 'mfr-current-tools',
  brand: 'Current Tools',
  family: '77 Series',
  series: 'Electric bender',
  modelNumbers: ['77', '77-EMT', '77-RIG', '77-IMC', '77-PVC'],
  skus: ['77', '77-EMT', '77-RIG', '77-IMC', '77-PVC'],
  aliases: [],
  category: 'electric',
  driveType: 'electric',
  material: null,
  marketStatus: 'active',
  regions: ['US'],
  supportedConduitTypes: ['EMT', 'IMC', 'RMC'],
  supportedNominalSizes: ['1/2', '3/4', '1', '1-1/4', '1-1/2', '2'],
  sourceIds: ['src-current-tools-77'],
  notes: 'Stub-up charts on pages 20-23 — extract before promoting.',
  researchClass: 'identity_verified',
  operationMode: 'one_shot',
});

// Greenlee hydraulic 881 family + shoe
addModel({
  id: 'model-greenlee-881',
  manufacturerId: 'mfr-greenlee',
  brand: 'Greenlee',
  family: '881 Cam-Track',
  series: '881 hydraulic Cam-Track bender',
  modelNumbers: ['881', '881CT', '881GX', '881GXD', '881GXE980', '881GXDE980'],
  skus: ['881', '881CT', '881GX', '881GXD'],
  aliases: ['Cam-Track'],
  category: 'hydraulic',
  driveType: 'hydraulic',
  material: null,
  marketStatus: 'active',
  regions: ['US'],
  supportedConduitTypes: ['EMT', 'IMC', 'RMC'],
  supportedNominalSizes: ['2-1/2', '3', '3-1/2', '4'],
  sourceIds: ['src-greenlee-2015-bending-catalog', 'src-greenlee-881-4in-shoe-31274'],
  notes: 'Frame family; radii on shoe groups.',
  researchClass: 'identity_verified',
  operationMode: 'one_shot',
});
addModel({
  id: 'model-greenlee-31274',
  manufacturerId: 'mfr-greenlee',
  brand: 'Greenlee',
  family: '881 Cam-Track',
  series: '881 CT 4-inch one-shot shoe group',
  modelNumbers: ['31274'],
  skus: ['31274'],
  aliases: [],
  category: 'shoe',
  driveType: 'n/a',
  material: 'aluminum',
  marketStatus: 'active',
  regions: ['US'],
  supportedConduitTypes: ['EMT', 'IMC', 'RMC'],
  supportedNominalSizes: ['4'],
  sourceIds: ['src-greenlee-881-4in-shoe-31274'],
  notes: '',
  researchClass: 'chart_candidate',
  parentFrameModelId: 'model-greenlee-881',
  operationMode: 'one_shot',
});
addFact({
  id: 'fact-31274-clr',
  modelId: 'model-greenlee-31274',
  conduitType: 'EMT',
  nominalSize: '4',
  property: 'centerline_radius',
  originalLabel: 'Centerline Bend Radius',
  originalValue: '20-7/8',
  originalUnit: 'inch',
  sourceId: 'src-greenlee-881-4in-shoe-31274',
  section: 'Specifications',
  excerpt: 'Centerline Bend Radius 20-7/8 in',
  evidenceStatus: 'official_exact',
  confidence: 'high',
  productionScope: 'out_of_production_scope',
  notes: 'Product page lists EMT, IMC, Rigid capacity for this shoe.',
});

// 2015 catalog 881 CT radii (EMT/IMC/Rigid shoe groups in catalog)
for (const [size, radius, cat] of [
  ['2-1/2', '13-1/2', '27554'],
  ['3', '16', '27555'],
  ['3-1/2', '18-5/8', '31281'],
  ['4', '20-7/8', '31274'],
]) {
  const id = `model-greenlee-${cat}`;
  if (!models.find((m) => m.id === id)) {
    addModel({
      id,
      manufacturerId: 'mfr-greenlee',
      brand: 'Greenlee',
      family: '881 Cam-Track',
      series: '881 CT shoe group',
      modelNumbers: [cat],
      skus: [cat],
      aliases: [],
      category: 'shoe',
      driveType: 'n/a',
      material: null,
      marketStatus: size === '4' ? 'active' : 'unknown',
      regions: ['US'],
      supportedConduitTypes: ['EMT', 'IMC', 'RMC'],
      supportedNominalSizes: [size],
      sourceIds: ['src-greenlee-2015-bending-catalog'],
      notes: 'From 2015 catalog — confirm current status on greenlee.com before promotion.',
      researchClass: size === '4' ? 'chart_candidate' : 'reference_only',
      parentFrameModelId: 'model-greenlee-881',
      operationMode: 'one_shot',
    });
  }
  if (cat !== '31274') {
    addFact({
      id: `fact-${cat}-clr-catalog`,
      modelId: id,
      conduitType: 'EMT',
      nominalSize: size,
      property: 'centerline_radius',
      originalLabel: 'Center line Radius',
      originalValue: radius,
      originalUnit: 'inch',
      sourceId: 'src-greenlee-2015-bending-catalog',
      table: '881 CT BASIC SIZE Center line Radius Shoe Group',
      excerpt: `${size} CLR ${radius} shoe ${cat}`,
      evidenceStatus: 'archived_official',
      confidence: 'medium',
      productionScope: 'out_of_production_scope',
    });
  }
}

// 884/885 rigid radii — out of scope reference
addModel({
  id: 'model-greenlee-885',
  manufacturerId: 'mfr-greenlee',
  brand: 'Greenlee',
  family: '885',
  series: 'Hydraulic bender 884/885',
  modelNumbers: ['884', '885'],
  skus: ['884', '885'],
  aliases: [],
  category: 'hydraulic',
  driveType: 'hydraulic',
  material: null,
  marketStatus: 'legacy-common',
  regions: ['US'],
  supportedConduitTypes: ['RMC'],
  supportedNominalSizes: ['1/2', '3/4', '1', '1-1/4', '1-1/2', '2', '2-1/2', '3', '3-1/2', '4', '5'],
  sourceIds: ['src-greenlee-884-885-radii-cdn'],
  notes: 'Radii table labeled Rigid Shoe Size — research-only for EMT app.',
  researchClass: 'reference_only',
  operationMode: 'segmented',
});

// RIDGID / Benfield / NSI / Chicago placeholders
addModel({
  id: 'model-ridgid-e666',
  manufacturerId: 'mfr-ridgid',
  brand: 'RIDGID',
  family: 'E-666',
  series: 'Electric conduit bender',
  modelNumbers: ['E-666'],
  skus: ['E-666'],
  aliases: ['E-665TL-90'],
  category: 'electric',
  driveType: 'electric',
  material: null,
  marketStatus: 'unknown',
  regions: ['UK', 'US'],
  supportedConduitTypes: ['EMT', 'IMC', 'RMC'],
  supportedNominalSizes: ['1/2', '3/4', '1', '1-1/4', '1-1/2', '2'],
  sourceIds: ['src-ridgid-e666-distributor'],
  notes: 'Distributor claim only until RIDGID official manual found.',
  researchClass: 'blocked_source',
  operationMode: 'one_shot',
});
addModel({
  id: 'model-benfield-method-reference',
  manufacturerId: 'mfr-benfield',
  brand: 'Benfield',
  family: 'Benfield method',
  series: 'Instructional / historic',
  modelNumbers: [],
  skus: [],
  aliases: ['Benfield style'],
  category: 'unknown',
  driveType: 'unknown',
  material: null,
  marketStatus: 'legacy-common',
  regions: ['US'],
  supportedConduitTypes: ['EMT'],
  supportedNominalSizes: [],
  sourceIds: ['src-benfield-manual-lead'],
  notes: 'Not a SKU. Method literature only.',
  researchClass: 'reference_only',
});
addModel({
  id: 'model-nsi-placeholder',
  manufacturerId: 'mfr-nsi',
  brand: 'NSI',
  family: 'unknown',
  series: 'Research lead',
  modelNumbers: [],
  skus: [],
  aliases: ['Tork'],
  category: 'unknown',
  driveType: 'unknown',
  material: null,
  marketStatus: 'unknown',
  regions: ['US'],
  supportedConduitTypes: ['unknown'],
  supportedNominalSizes: [],
  sourceIds: [],
  notes: 'No authoritative conduit bender chart located in this research pass.',
  researchClass: 'blocked_source',
});
addModel({
  id: 'model-chicago-ratchet-legacy',
  manufacturerId: 'mfr-emerson-chicago',
  brand: 'Chicago / Emerson legacy',
  family: 'Chicago ratchet',
  series: 'Legacy mechanical ratchet',
  modelNumbers: [],
  skus: [],
  aliases: ['Chicago bender'],
  category: 'mechanical',
  driveType: 'ratchet',
  material: null,
  marketStatus: 'legacy-common',
  regions: ['US'],
  supportedConduitTypes: ['EMT', 'RMC'],
  supportedNominalSizes: [],
  sourceIds: ['src-benfield-manual-lead'],
  notes: 'Trade name class; needs identifiable OEM manual before SKU/facts.',
  researchClass: 'reference_only',
  operationMode: 'one_shot',
});

// Fix conflict-ideal competingFactIds (need 2 distinct) — add placeholder missing fact
addFact({
  id: 'fact-ideal-74-006-stub-unknown',
  modelId: 'model-ideal-74-034',
  conduitType: 'EMT',
  nominalSize: '1-1/4',
  property: 'stub_take_up',
  originalLabel: 'Stub Up Height (74-006 — not yet confirmed)',
  originalValue: null,
  originalUnit: 'unknown',
  normalizedValueInches: null,
  sourceId: 'src-ideal-74-006-related',
  evidenceStatus: 'missing',
  confidence: 'none',
  notes: 'Related catalog SKU 74-006 may be the head-only counterpart; value unknown.',
  conflictGroupId: 'conflict-ideal-114-sku',
});
conflicts.find((c) => c.id === 'conflict-ideal-114-sku').competingFactIds = [
  'fact-ideal-74-034-stub-prod-mirror',
  'fact-ideal-74-006-stub-unknown',
];

// --- Additional identity / accessory expansions (no invented numbers) ---
for (const [sku, size] of [
  ['51611', '1/2'],
  ['51612', '3/4'],
  ['51613', '1'],
]) {
  addModel({
    id: `model-klein-${sku}`,
    manufacturerId: 'mfr-klein',
    brand: 'Klein Tools',
    family: 'Angle Setter',
    series: 'Angle Setter accessory',
    modelNumbers: [sku],
    skus: [sku],
    aliases: ['Angle Setter stop'],
    category: 'accessory',
    driveType: 'n/a',
    material: null,
    marketStatus: 'active',
    regions: ['US'],
    supportedConduitTypes: ['EMT'],
    supportedNominalSizes: [size],
    sourceIds: ['src-klein-51604', 'src-klein-51606'],
    notes: 'Angle Setter hard-stop accessory — not a shoe chart.',
    researchClass: 'identity_verified',
    operationMode: 'n/a',
  });
}

addModel({
  id: 'model-klein-51427',
  manufacturerId: 'mfr-klein',
  brand: 'Klein Tools',
  family: 'Angle Setter',
  series: 'Handle',
  modelNumbers: ['51427'],
  skus: ['51427'],
  aliases: [],
  category: 'accessory',
  driveType: 'n/a',
  material: null,
  marketStatus: 'active',
  regions: ['US'],
  supportedConduitTypes: ['EMT'],
  supportedNominalSizes: ['1/2', '3/4'],
  sourceIds: ['src-klein-51604'],
  notes: 'Handle for 1/2 and 3/4 heads.',
  researchClass: 'identity_verified',
  operationMode: 'n/a',
});

for (const sku of ['74-019', '74-020', '74-021']) {
  addModel({
    id: `model-ideal-${sku}`,
    manufacturerId: 'mfr-ideal',
    brand: 'IDEAL',
    family: 'IDEAL hand bender',
    series: 'Bender handle',
    modelNumbers: [sku],
    skus: [sku],
    aliases: [],
    category: 'accessory',
    driveType: 'n/a',
    material: null,
    marketStatus: 'active',
    regions: ['US'],
    supportedConduitTypes: ['EMT'],
    supportedNominalSizes: [],
    sourceIds: ['src-ideal-74-031'],
    notes: 'Handle SKUs from related products on aluminum head pages.',
    researchClass: 'identity_verified',
    operationMode: 'n/a',
  });
}

addModel({
  id: 'model-ideal-74-006',
  manufacturerId: 'mfr-ideal',
  brand: 'IDEAL',
  family: 'IDEAL hand bender',
  series: 'Ductile iron hand bender',
  modelNumbers: ['74-006'],
  skus: ['74-006'],
  aliases: [],
  category: 'hand',
  driveType: 'manual',
  material: 'ductile iron',
  marketStatus: 'unknown',
  regions: ['US', 'CA'],
  supportedConduitTypes: ['EMT'],
  supportedNominalSizes: ['1-1/4'],
  sourceIds: ['src-ideal-74-006-related'],
  notes: 'Cited in related products as 1-1/4 EMT head; stub-up not yet captured from dedicated page.',
  researchClass: 'conflict_review',
});

// Gardner iron / malleable catalog identities from archived catalog lead (no numbers promoted)
for (const [sku, size] of [
  ['920', '1/2'],
  ['921', '3/4'],
  ['922', '1'],
  ['923', '1-1/4'],
  ['930B', '1/2'],
  ['931B', '3/4'],
  ['932', '1'],
]) {
  addModel({
    id: `model-gardner-${sku.toLowerCase()}`,
    manufacturerId: 'mfr-gardner-bender',
    brand: 'Gardner Bender',
    family: sku.startsWith('9') && sku.length <= 3 ? 'Malleable iron hand' : 'Gardner hand',
    series: 'Legacy / catalog hand bender',
    modelNumbers: [sku],
    skus: [sku],
    aliases: [],
    category: 'hand',
    driveType: 'manual',
    material: sku.startsWith('92') ? 'malleable iron' : null,
    marketStatus: 'legacy-common',
    regions: ['US'],
    supportedConduitTypes: ['EMT'],
    supportedNominalSizes: [size],
    sourceIds: ['src-gardner-howto-gar-bro-032'],
    notes:
      'Identity from Gardner catalog/index leads (inspectapedia-hosted catalog scan used as discovery). No take-up promoted without official chart row.',
    researchClass: 'reference_only',
  });
}

addModel({
  id: 'model-greenlee-13934',
  manufacturerId: 'mfr-greenlee',
  brand: 'Greenlee',
  family: '555',
  series: '555 EMT shoe group (alternate catalog #)',
  modelNumbers: ['13934'],
  skus: ['13934'],
  aliases: [],
  category: 'shoe',
  driveType: 'n/a',
  material: null,
  marketStatus: 'unknown',
  regions: ['US'],
  supportedConduitTypes: ['EMT'],
  supportedNominalSizes: ['1/2', '3/4', '1', '1-1/4', '1-1/2', '2'],
  sourceIds: ['src-greenlee-2015-bending-catalog', 'src-greenlee-555-single-shoe-52065584-rev02'],
  notes: '2015 catalog lists 13934 EMT shoe group for some 555 variants — confirm current mapping vs 23803.',
  researchClass: 'reference_only',
  parentFrameModelId: 'model-greenlee-555c',
  operationMode: 'one_shot',
});

addModel({
  id: 'model-greenlee-28008',
  manufacturerId: 'mfr-greenlee',
  brand: 'Greenlee',
  family: '555',
  series: '555 Rigid shoe group',
  modelNumbers: ['28008'],
  skus: ['28008'],
  aliases: [],
  category: 'shoe',
  driveType: 'n/a',
  material: null,
  marketStatus: 'active',
  regions: ['US'],
  supportedConduitTypes: ['RMC', 'IMC'],
  supportedNominalSizes: ['1/2', '3/4', '1', '1-1/4', '1-1/2', '2'],
  sourceIds: ['src-greenlee-555-single-shoe-52065584-rev02'],
  notes: 'Rigid shoe group — out of EMT production scope for numbers unless separately extracted.',
  researchClass: 'identity_verified',
  parentFrameModelId: 'model-greenlee-555c',
  operationMode: 'one_shot',
});

addModel({
  id: 'model-greenlee-855gx',
  manufacturerId: 'mfr-greenlee',
  brand: 'Greenlee',
  family: '855',
  series: '855GX electric/table bender',
  modelNumbers: ['855GX'],
  skus: ['855GX'],
  aliases: [],
  category: 'electric',
  driveType: 'electric',
  material: null,
  marketStatus: 'active',
  regions: ['US'],
  supportedConduitTypes: ['EMT', 'IMC', 'RMC'],
  supportedNominalSizes: ['1', '1-1/4', '1-1/2', '2'],
  sourceIds: ['src-greenlee-2015-bending-catalog'],
  notes: 'Catalog mentions stainless EMT capabilities — confirm current product page before charts.',
  researchClass: 'reference_only',
  operationMode: 'one_shot',
});

addModel({
  id: 'model-greenlee-880',
  manufacturerId: 'mfr-greenlee',
  brand: 'Greenlee',
  family: '880',
  series: 'Hydraulic bender 880',
  modelNumbers: ['880', '880H755', '880E975'],
  skus: ['880'],
  aliases: [],
  category: 'hydraulic',
  driveType: 'hydraulic',
  material: null,
  marketStatus: 'legacy-common',
  regions: ['US'],
  supportedConduitTypes: ['RMC'],
  supportedNominalSizes: ['1', '1-1/4', '1-1/2', '2'],
  sourceIds: ['src-greenlee-2015-bending-catalog'],
  notes: '2015 catalog capacity Rigid 1-2; radii table Rigid — research-only.',
  researchClass: 'reference_only',
  operationMode: 'one_shot',
});

addModel({
  id: 'model-current-700e',
  manufacturerId: 'mfr-current-tools',
  brand: 'Current Tools',
  family: '77 Series',
  series: 'EMT shoe set for 77',
  modelNumbers: ['700E'],
  skus: ['700E'],
  aliases: [],
  category: 'shoe',
  driveType: 'n/a',
  material: null,
  marketStatus: 'active',
  regions: ['US'],
  supportedConduitTypes: ['EMT'],
  supportedNominalSizes: ['1/2', '3/4', '1', '1-1/4', '1-1/2', '2'],
  sourceIds: ['src-current-tools-77'],
  notes: 'EMT shoe kit referenced in 77 series manual.',
  researchClass: 'identity_verified',
  parentFrameModelId: 'model-current-77',
  operationMode: 'one_shot',
});


fs.mkdirSync(DATA, { recursive: true });
fs.writeFileSync(
  path.join(DATA, 'manufacturers.json'),
  JSON.stringify({ schemaVersion: '1.0.0', retrievedDate: DATE, manufacturers }, null, 2),
);
fs.writeFileSync(
  path.join(DATA, 'sources.json'),
  JSON.stringify({ schemaVersion: '1.0.0', retrievedDate: DATE, sources }, null, 2),
);
fs.writeFileSync(
  path.join(DATA, 'models.json'),
  JSON.stringify({ schemaVersion: '1.0.0', retrievedDate: DATE, models }, null, 2),
);
fs.writeFileSync(
  path.join(DATA, 'measurements.json'),
  JSON.stringify({ schemaVersion: '1.0.0', retrievedDate: DATE, measurements }, null, 2),
);
fs.writeFileSync(
  path.join(DATA, 'conflicts.json'),
  JSON.stringify({ schemaVersion: '1.0.0', retrievedDate: DATE, conflicts }, null, 2),
);

console.log(
  JSON.stringify(
    {
      manufacturers: manufacturers.length,
      sources: sources.length,
      models: models.length,
      measurements: measurements.length,
      conflicts: conflicts.length,
    },
    null,
    2,
  ),
);
